### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by SerhiiNesteruk** [scredis/scredis#146]
if the record is moved client cant parse ipv6 address:

```
scredis.exceptions.RedisProtocolException: Could not decode response
	at scredis.io.DecoderActor$$anonfun$receive$1.applyOrElse(DecoderActor.scala:36)
	at akka.actor.Actor.aroundReceive(Actor.scala:533)
	at akka.actor.Actor.aroundReceive$(Actor.scala:531)
	at scredis.io.DecoderActor.aroundReceive(DecoderActor.scala:12)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
	at akka.actor.ActorCell.invoke(ActorCell.scala:543)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: scredis.exceptions.RedisProtocolException: invalid format for MOVED or ASK error: MOVED 7310 xxxx:xxxx:xxx:xxxx:xxxx:x:x:xxx:6379
	at scredis.protocol.Protocol$.decodeError(Protocol.scala:296)
	at scredis.protocol.Protocol$.decode(Protocol.scala:276)
	at scredis.io.DecoderActor$$anonfun$receive$1.applyOrElse(DecoderActor.scala:31)
	... 12 common frames omitted
Caused by: java.lang.NumberFormatException: For input string: "xxxx:xxx:xxxx:xxxx:x:x:xxx:6379"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at scredis.protocol.Protocol$.decodeMoveAsk(Protocol.scala:315)
	at scredis.protocol.Protocol$.decodeError(Protocol.scala:293)
	... 14 common frames omitted
```

client version: 2.3.4

**Comment by kpbochenek** [comment]
Thanks for reporting!

It was indeed handled wrongly :/
